-- 1.


--2.

--3.



--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING( CLASS_NO )
JOIN TB_PROFESSOR USING( PROFESSOR_NO );

--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP USING( CLASS_NO )
JOIN TB_PROFESSOR USING( PROFESSOR_NO )
JOIN TB_DEPARTMENT D ON( D.DEPARTMENT_NO = C.DEPARTMENT_NO )
WHERE CATEGORY = '인문사회';

--13. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING( CLASS_NO )
LEFT JOIN TB_DEPARTMENT USING( DEPARTMENT_NO )  --NULL값도 나와야되면 LEFT JOIN이나 RIGHT JOIN을 써야함
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

--19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND( AVG( POINT ),1 ) 전공평점
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING( DEPARTMENT_NO )
JOIN TB_GRADE USING( STUDENT_NO )
WHERE CATEGORY = ( SELECT CATEGORY
                                        FROM TB_DEPARTMENT
                                        WHERE DEPARTMENT_NAME = '환경조경학과' )
GROUP BY DEPARTMENT_NAME;   --AVG가 있어서 그룹 지어줘야함

























