CREATE TABLE REPLY(
        NO NUMBER PRIMARY KEY,
        CONTENT VARCHAR2(400),
        REF NUMBER,
        NAME VARCHAR2(20),
        REDATE DATE
);

CREATE SEQUENCE SEQ_REPLY NOCACHE;

INSERT INTO REPLY VALUES(SEQ_REPLY.NEXTVAL,'와! 첫 댓글', 1, '김처음', '2023/12/02');
INSERT INTO REPLY VALUES(SEQ_REPLY.NEXTVAL,'멋지군요', 1, '박멋짐', '2023/12/12');
INSERT INTO REPLY VALUES(SEQ_REPLY.NEXTVAL,'굉장하군요', 1, '이괴장', '2023/12/15');
INSERT INTO REPLY VALUES(SEQ_REPLY.NEXTVAL,'아름다워요', 1, '황아름', '2024/01/03');

commit;